### ISSUE TITLE
Add an export button functionality 

### ISSUE THREAD

**Issue by 19arnab190201** [hash-define-organization/Hash-Whiteboard#46]
an export button functionality where users can export their drawing / creatives into image format

**Comment by Shubham29012001** [comment]
Hey @19arnab190201, I would like to work on this functionality as a GSSoC'22 contributor. Can you please assign it to me?

**Comment by Shubham29012001** [comment]
Hey @19arnab190201, I have developed the mentioned functionality i.e. The user can download their sketch as a PNG file when clicking on the File-Download icon.

Here is the working screenshot -

![image](https://user-images.githubusercontent.com/59647563/162567723-ac8af9ca-004c-48bf-8f08-cb3c78da3092.png)

Here is the download image -

![image](https://user-images.githubusercontent.com/59647563/162567762-96f2af12-1348-4ade-bfab-c203be54c256.png)

Can you please assign it to me under the GSSoC'22 label so that I can create a PR for it?

**Comment by Shubham29012001** [comment]
Fix #49
